sonar.projectKey=eks-retail-platform
sonar.organization=${SONAR_ORG}

sonar.sources=apps/
sonar.tests=apps/
sonar.test.inclusions=**/tests/**
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/venv/**

sonar.python.coverage.reportPaths=apps/*/coverage.xml
sonar.python.version=3.12

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
