{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: audit-pipeline
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "audit-pipeline.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "audit-pipeline.selectorLabels" . | nindent 6 }}
{{- end }}
