"""Tool 1: IaC Generator — Generate Terraform from YAML service descriptions."""

from __future__ import annotations

import os
from pathlib import Path
from typing import Dict, Any

import yaml
from jinja2 import Template

from core.analyzer import BaseAnalyzer, AnalysisResult, Severity, Category


# ── Terraform Templates ──────────────────────────────────────────────────────

VPC_TEMPLATE = Template('''\
# Auto-generated by Claude DevOps Debug Toolkit — IaC Generator
# Service: {{ service_name }}

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      ManagedBy   = "{{ tags.managed_by | default('terraform') }}"
      Team        = "{{ tags.team | default('platform') }}"
      CostCenter  = "{{ tags.cost_center | default('engineering') }}"
      Environment = var.environment
    }
  }
}

# ── Variables ──────────────────────────────────────────────────
variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "{{ environment }}"
}

# ── VPC ────────────────────────────────────────────────────────
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 5.0"

  name = "{{ service_name }}-vpc"
  cidr = "{{ vpc.cidr }}"

  azs             = [for az in range({{ vpc.azs }}): "${var.aws_region}${["a","b","c","d"][az]}"]
  private_subnets = [for i in range({{ vpc.azs }}): cidrsubnet("{{ vpc.cidr }}", 8, i)]
  public_subnets  = [for i in range({{ vpc.azs }}): cidrsubnet("{{ vpc.cidr }}", 8, i + 100)]

  enable_nat_gateway   = {{ 'true' if vpc.nat_gateway else 'false' }}
  single_nat_gateway   = var.environment != "production"
  enable_dns_hostnames = true
  enable_dns_support   = true

  # EKS subnet tags
  private_subnet_tags = {
    "kubernetes.io/role/internal-elb" = "1"
  }
  public_subnet_tags = {
    "kubernetes.io/role/elb" = "1"
  }
}

# ── VPC Flow Logs ──────────────────────────────────────────────
resource "aws_flow_log" "vpc" {
  vpc_id               = module.vpc.vpc_id
  traffic_type         = "ALL"
  log_destination_type = "cloud-watch-logs"
  log_destination      = aws_cloudwatch_log_group.flow_logs.arn
  iam_role_arn         = aws_iam_role.flow_logs.arn
}

resource "aws_cloudwatch_log_group" "flow_logs" {
  name              = "/vpc/{{ service_name }}/flow-logs"
  retention_in_days = 30
}

resource "aws_iam_role" "flow_logs" {
  name = "{{ service_name }}-flow-logs-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = { Service = "vpc-flow-logs.amazonaws.com" }
    }]
  })
}
''')

EKS_TEMPLATE = Template('''\
# ── EKS Cluster ────────────────────────────────────────────────
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 20.0"

  cluster_name    = "{{ cluster_name }}"
  cluster_version = "1.30"

  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets

  cluster_endpoint_public_access  = true
  cluster_endpoint_private_access = true

  enable_irsa = true

  cluster_addons = {
    coredns    = { most_recent = true }
    kube-proxy = { most_recent = true }
    vpc-cni    = { most_recent = true }
    aws-ebs-csi-driver = { most_recent = true }
  }

  eks_managed_node_groups = {
{% for ng in node_groups %}
    {{ ng.name }} = {
      instance_types = ["{{ ng.instance_type }}"]
      min_size       = {{ ng.min_size }}
      max_size       = {{ ng.max_size }}
      desired_size   = {{ ng.desired_size }}

      labels = {
        role = "{{ ng.name }}"
      }
    }
{% endfor %}
  }
}
''')

DB_TEMPLATE = Template('''\
# ── Aurora Database ────────────────────────────────────────────
module "aurora" {
  source  = "terraform-aws-modules/rds-aurora/aws"
  version = "~> 9.0"

  name            = "{{ service_name }}-db"
  engine          = "aurora-postgresql"
  engine_version  = "{{ engine_version }}"
  instance_class  = "{{ instance_class }}"
  instances       = { for i in range({{ instances }}): "instance-${i}" => {} }

  vpc_id  = module.vpc.vpc_id
  subnets = module.vpc.private_subnets

  storage_encrypted   = {{ 'true' if encrypted else 'false' }}
  apply_immediately   = false
  skip_final_snapshot = var.environment != "production"

  backup_retention_period = {{ backup_retention | default(7) }}

  security_group_rules = {
    ingress = {
      cidr_blocks = module.vpc.private_subnets_cidr_blocks
    }
  }
}
''')

S3_TEMPLATE = Template('''\
# ── S3 Bucket: {{ bucket.name }} ──────────────────────────────
resource "aws_s3_bucket" "{{ bucket.name | replace('-', '_') }}" {
  bucket = "${var.environment}-{{ bucket.name }}"
}

resource "aws_s3_bucket_versioning" "{{ bucket.name | replace('-', '_') }}" {
  bucket = aws_s3_bucket.{{ bucket.name | replace('-', '_') }}.id
  versioning_configuration {
    status = "{{ 'Enabled' if bucket.versioning else 'Disabled' }}"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "{{ bucket.name | replace('-', '_') }}" {
  bucket = aws_s3_bucket.{{ bucket.name | replace('-', '_') }}.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "aws:kms"
    }
  }
}

resource "aws_s3_bucket_public_access_block" "{{ bucket.name | replace('-', '_') }}" {
  bucket                  = aws_s3_bucket.{{ bucket.name | replace('-', '_') }}.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
{% if bucket.lifecycle %}
resource "aws_s3_bucket_lifecycle_configuration" "{{ bucket.name | replace('-', '_') }}" {
  bucket = aws_s3_bucket.{{ bucket.name | replace('-', '_') }}.id
  rule {
    id     = "lifecycle"
    status = "Enabled"
{% if bucket.lifecycle.transition_to_ia %}
    transition {
      days          = {{ bucket.lifecycle.transition_to_ia }}
      storage_class = "STANDARD_IA"
    }
{% endif %}
{% if bucket.lifecycle.transition_to_glacier %}
    transition {
      days          = {{ bucket.lifecycle.transition_to_glacier }}
      storage_class = "GLACIER"
    }
{% endif %}
  }
}
{% endif %}
''')


class IaCGenerator(BaseAnalyzer):
    """Generate Terraform HCL from YAML service descriptions."""

    name = "IaC Generator"
    version = "1.0.0"

    def analyze(self, target: str, **kwargs) -> AnalysisResult:
        """Analyze a service description YAML and generate Terraform."""
        target_path = Path(target)
        output_dir = kwargs.get("output_dir", "output")

        if not target_path.exists():
            self._add_finding(
                "IAC000", Severity.CRITICAL, Category.CONFIGURATION,
                "Input file not found", f"File not found: {target}",
                recommendation="Provide a valid YAML service description file."
            )
            return self._build_result(target)

        with open(target_path, "r", encoding="utf-8") as f:
            spec = yaml.safe_load(f)

        if not spec:
            self._add_finding(
                "IAC001", Severity.CRITICAL, Category.CONFIGURATION,
                "Empty service description", "YAML file is empty or invalid.",
                recommendation="Provide a valid service description with infrastructure section."
            )
            return self._build_result(target)

        generated_files = self._generate(spec, output_dir)

        self._add_finding(
            "IAC100", Severity.INFO, Category.CONFIGURATION,
            "Terraform files generated",
            f"Generated {len(generated_files)} Terraform files in {output_dir}/",
            recommendation="Review generated files, customize variables, and run 'terraform plan'."
        )

        return self._build_result(
            target,
            generated_files=generated_files,
            output_directory=output_dir,
        )

    def _generate(self, spec: Dict[str, Any], output_dir: str) -> list:
        """Generate Terraform files from the spec."""
        os.makedirs(output_dir, exist_ok=True)
        generated = []
        service = spec.get("service", {})
        infra = spec.get("infrastructure", {})
        tags = spec.get("tags", {})
        svc_name = service.get("name", "my-service")
        env = service.get("environment", "production")

        # VPC
        if "vpc" in infra:
            content = VPC_TEMPLATE.render(
                service_name=svc_name, environment=env,
                vpc=infra["vpc"], tags=tags,
            )
            path = os.path.join(output_dir, "main.tf")
            Path(path).write_text(content, encoding="utf-8")
            generated.append("main.tf")

        # EKS
        if "compute" in infra and infra["compute"].get("type") == "eks":
            compute = infra["compute"]
            content = EKS_TEMPLATE.render(
                cluster_name=compute.get("cluster_name", f"{svc_name}-cluster"),
                node_groups=compute.get("node_groups", []),
            )
            path = os.path.join(output_dir, "eks.tf")
            Path(path).write_text(content, encoding="utf-8")
            generated.append("eks.tf")

        # Database
        if "database" in infra:
            db = infra["database"]
            content = DB_TEMPLATE.render(
                service_name=svc_name, **db,
            )
            path = os.path.join(output_dir, "database.tf")
            Path(path).write_text(content, encoding="utf-8")
            generated.append("database.tf")

        # S3
        if "storage" in infra and "s3_buckets" in infra["storage"]:
            parts = []
            for bucket in infra["storage"]["s3_buckets"]:
                parts.append(S3_TEMPLATE.render(bucket=bucket))
            path = os.path.join(output_dir, "storage.tf")
            Path(path).write_text("\n".join(parts), encoding="utf-8")
            generated.append("storage.tf")

        return generated
