"""Tool 7: Runbook Generator — Generate operational runbooks from IaC manifests."""

from __future__ import annotations

import re
from pathlib import Path
from typing import List, Dict

from core.analyzer import BaseAnalyzer, AnalysisResult, Severity, Category
from core.file_utils import discover_files, read_file


class RunbookGenerator(BaseAnalyzer):
    """Generate operational runbooks from Terraform or K8s manifests."""

    name = "Runbook Generator"
    version = "1.0.0"

    def analyze(self, target: str, **kwargs) -> AnalysisResult:
        """Analyze infrastructure files and generate a runbook."""
        target_path = Path(target)
        output_path = kwargs.get("output", "reports/runbook.md")

        tf_files = discover_files(target_path, extensions=[".tf"])
        k8s_files = discover_files(target_path, extensions=[".yaml", ".yml"])

        resources = []
        for fpath in tf_files:
            content = read_file(fpath)
            resources.extend(self._extract_tf_resources(content, fpath.name))

        k8s_objects = []
        for fpath in k8s_files:
            content = read_file(fpath)
            k8s_objects.extend(self._extract_k8s_objects(content, fpath.name))

        if not resources and not k8s_objects:
            self._add_finding(
                "RUN000", Severity.INFO, Category.CONFIGURATION,
                "No infrastructure found", "No Terraform resources or K8s manifests detected.",
            )
            return self._build_result(target)

        runbook = self._generate_runbook(resources, k8s_objects)
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        Path(output_path).write_text(runbook, encoding="utf-8")

        self._add_finding(
            "RUN100", Severity.INFO, Category.CONFIGURATION,
            "Runbook generated successfully",
            f"Generated runbook with {len(resources)} Terraform resources and {len(k8s_objects)} K8s objects.",
            location=output_path,
            recommendation="Review and customize the generated runbook for your team."
        )

        return self._build_result(
            target,
            output_file=output_path,
            terraform_resources=len(resources),
            k8s_objects=len(k8s_objects),
        )

    def _extract_tf_resources(self, content: str, filename: str) -> List[Dict]:
        """Extract Terraform resource definitions."""
        resources = []
        pattern = re.compile(r'resource\s+"([^"]+)"\s+"([^"]+)"', re.MULTILINE)
        for m in pattern.finditer(content):
            resources.append({"type": m.group(1), "name": m.group(2), "file": filename})
        return resources

    def _extract_k8s_objects(self, content: str, filename: str) -> List[Dict]:
        """Extract Kubernetes object definitions."""
        objects = []
        for doc in content.split("---"):
            kind_match = re.search(r'kind:\s*(\S+)', doc)
            name_match = re.search(r'name:\s*(\S+)', doc)
            if kind_match:
                objects.append({
                    "kind": kind_match.group(1),
                    "name": name_match.group(1) if name_match else "unnamed",
                    "file": filename,
                })
        return objects

    def _generate_runbook(self, resources: List[Dict], k8s_objects: List[Dict]) -> str:
        """Generate a markdown runbook."""
        sections = [
            "# 📋 Operational Runbook",
            "",
            "> Auto-generated by Claude DevOps Debug Toolkit",
            "",
            "## Table of Contents",
            "1. [Infrastructure Overview](#infrastructure-overview)",
            "2. [Deployment Procedure](#deployment-procedure)",
            "3. [Health Checks](#health-checks)",
            "4. [Scaling Procedures](#scaling-procedures)",
            "5. [Rollback Procedure](#rollback-procedure)",
            "6. [Incident Response](#incident-response)",
            "7. [Maintenance Windows](#maintenance-windows)",
            "",
            "---",
            "",
            "## Infrastructure Overview",
            "",
        ]

        if resources:
            sections.append("### Terraform Resources")
            sections.append("")
            sections.append("| Type | Name | File |")
            sections.append("|------|------|------|")
            for r in resources:
                sections.append(f"| `{r['type']}` | `{r['name']}` | `{r['file']}` |")
            sections.append("")

        if k8s_objects:
            sections.append("### Kubernetes Objects")
            sections.append("")
            sections.append("| Kind | Name | File |")
            sections.append("|------|------|------|")
            for obj in k8s_objects:
                sections.append(f"| `{obj['kind']}` | `{obj['name']}` | `{obj['file']}` |")
            sections.append("")

        # Standard runbook sections
        sections.extend([
            "---",
            "",
            "## Deployment Procedure",
            "",
            "### Pre-Deployment Checklist",
            "- [ ] All tests passing in CI/CD pipeline",
            "- [ ] Code reviewed and approved",
            "- [ ] Change request documented",
            "- [ ] Rollback plan verified",
            "- [ ] Monitoring dashboards ready",
            "",
            "### Terraform Deployment",
            "```bash",
            "# 1. Initialize",
            "terraform init",
            "",
            "# 2. Plan and review",
            "terraform plan -out=tfplan",
            "",
            "# 3. Apply (after review)",
            "terraform apply tfplan",
            "",
            "# 4. Verify",
            "terraform show",
            "```",
            "",
            "### Kubernetes Deployment",
            "```bash",
            "# Using kubectl",
            "kubectl apply -f manifests/ --dry-run=client",
            "kubectl apply -f manifests/",
            "kubectl rollout status deployment/<name> -n <namespace>",
            "",
            "# Using ArgoCD",
            "argocd app sync <app-name>",
            "argocd app wait <app-name>",
            "```",
            "",
            "---",
            "",
            "## Health Checks",
            "",
            "```bash",
            "# Kubernetes health",
            "kubectl get pods -n <namespace> -o wide",
            "kubectl top pods -n <namespace>",
            "kubectl get events -n <namespace> --sort-by='.lastTimestamp'",
            "",
            "# Application health",
            "curl -f http://<service>/healthz",
            "curl -f http://<service>/ready",
            "",
            "# AWS infrastructure",
            "aws rds describe-db-instances --query 'DBInstances[*].[DBInstanceIdentifier,DBInstanceStatus]'",
            "aws eks describe-cluster --name <cluster> --query 'cluster.status'",
            "```",
            "",
            "---",
            "",
            "## Scaling Procedures",
            "",
            "```bash",
            "# Scale Kubernetes deployment",
            "kubectl scale deployment/<name> --replicas=<count> -n <namespace>",
            "",
            "# Scale EKS node group",
            "aws eks update-nodegroup-config \\",
            "  --cluster-name <cluster> \\",
            "  --nodegroup-name <nodegroup> \\",
            "  --scaling-config minSize=<min>,maxSize=<max>,desiredSize=<desired>",
            "```",
            "",
            "---",
            "",
            "## Rollback Procedure",
            "",
            "### Kubernetes Rollback",
            "```bash",
            "kubectl rollout undo deployment/<name> -n <namespace>",
            "kubectl rollout status deployment/<name> -n <namespace>",
            "```",
            "",
            "### Terraform Rollback",
            "```bash",
            "# Revert to previous Git commit",
            "git revert HEAD",
            "terraform plan -out=rollback",
            "terraform apply rollback",
            "```",
            "",
            "---",
            "",
            "## Incident Response",
            "",
            "| Severity | Response Time | Escalation |",
            "|----------|--------------|------------|",
            "| SEV-1 (Critical) | 15 min | On-call → Team Lead → VP Eng |",
            "| SEV-2 (High) | 30 min | On-call → Team Lead |",
            "| SEV-3 (Medium) | 4 hours | On-call |",
            "| SEV-4 (Low) | Next business day | Ticket |",
            "",
            "### SEV-1 Response Template",
            "1. Acknowledge incident in PagerDuty/Slack",
            "2. Open incident bridge (video call link)",
            "3. Gather initial data: `kubectl get events`, CloudWatch metrics",
            "4. Identify blast radius and affected customers",
            "5. Implement fix or rollback",
            "6. Monitor for recovery",
            "7. Post-incident review within 48 hours",
            "",
            "---",
            "",
            "## Maintenance Windows",
            "",
            "| Activity | Window | Frequency |",
            "|----------|--------|-----------|",
            "| K8s version upgrade | Saturday 02:00-06:00 UTC | Quarterly |",
            "| RDS maintenance | Sunday 03:00-05:00 UTC | As needed |",
            "| SSL certificate renewal | Any time (zero-downtime) | Before expiry |",
            "| Node rotation | Tuesday 02:00-04:00 UTC | Monthly |",
        ])

        return "\n".join(sections)
