apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clearing-engine-gcp
  namespace: argocd
  labels:
    cloud: gcp
    role: compliance-analytics
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/multicloud-clearing-engine.git
    targetRevision: main
    path: gitops/apps/gcp
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: clearing-engine
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
