apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: 3-tier-app-eks
  labels:
    app.kubernetes.io/managed-by: pushparaj
data:
  FLASK_APP: "run.py"
  FLASK_DEBUG: "0"
  ALLOWED_ORIGINS: "https://your-domain.com,http://localhost:3000"
